// <auto-generated />
namespace Itanio.Leads.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MultiplosGuids : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MultiplosGuids));
        
        string IMigrationMetadata.Id
        {
            get { return "201605271430333_MultiplosGuids"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
